services:
  - type: web
    name: propfi
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
    plan: free